//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Systek.Server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServerContext : DbContext
    {
        public ServerContext()
            : base("name=ServerContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAreaType> tblAreaType { get; set; }
        public virtual DbSet<tblCommand> tblCommand { get; set; }
        public virtual DbSet<tblCommandSet> tblCommandSet { get; set; }
        public virtual DbSet<tblMessageLog> tblMessageLog { get; set; }
        public virtual DbSet<tblMessageType> tblMessageType { get; set; }
        public virtual DbSet<tblRole> tblRole { get; set; }
        public virtual DbSet<tblServer> tblServer { get; set; }
        public virtual DbSet<tblSystemLog> tblSystemLog { get; set; }
        public virtual DbSet<tblType> tblType { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<vLog> vLog { get; set; }
    }
}
