//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Systek.Utility
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// 
    /// </summary>
    public partial class tblMessageLog
    {
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>
        /// The identifier.
        /// </value>
        public int ID { get; set; }
        /// <summary>
        /// Gets or sets the user identifier.
        /// </summary>
        /// <value>
        /// The user identifier.
        /// </value>
        public int UserID { get; set; }
        /// <summary>
        /// Gets or sets the message type identifier.
        /// </summary>
        /// <value>
        /// The message type identifier.
        /// </value>
        public int MessageTypeID { get; set; }
        /// <summary>
        /// Gets or sets the command set identifier.
        /// </summary>
        /// <value>
        /// The command set identifier.
        /// </value>
        public Nullable<int> CommandSetID { get; set; }
        /// <summary>
        /// Gets or sets the t stamp.
        /// </summary>
        /// <value>
        /// The t stamp.
        /// </value>
        public System.DateTime tStamp { get; set; }

        /// <summary>
        /// Gets or sets the table command set.
        /// </summary>
        /// <value>
        /// The table command set.
        /// </value>
        public virtual tblCommandSet tblCommandSet { get; set; }
        /// <summary>
        /// Gets or sets the type of the table message.
        /// </summary>
        /// <value>
        /// The type of the table message.
        /// </value>
        public virtual tblMessageType tblMessageType { get; set; }
        /// <summary>
        /// Gets or sets the table user.
        /// </summary>
        /// <value>
        /// The table user.
        /// </value>
        public virtual tblUser tblUser { get; set; }
    }
}
