//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Systek.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSystemLog
    {
        public int ID { get; set; }
        public int typeID { get; set; }
        public int areaID { get; set; }
        public int serverID { get; set; }
        public string message { get; set; }
    
        public virtual tblAreaType tblAreaType { get; set; }
        public virtual tblServer tblServer { get; set; }
        public virtual tblType tblType { get; set; }
    }
}
