//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Systek.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblServer()
        {
            this.tblSystemLog = new HashSet<tblSystemLog>();
        }
    
        public int ID { get; set; }
        public string hostname { get; set; }
        public string ip { get; set; }
        public bool online { get; set; }
        public int roleID { get; set; }
    
        public virtual tblRole tblRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSystemLog> tblSystemLog { get; set; }
    }
}
